# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VrwoaDN50tQvQbOMJmSAgzMW_mDMrC7O
"""

import fixed_module

s = 4
d = 5
v = fixed_module.summa(s, d)
v

g = fixed_module.multi(s, d)

print(v)

print(g)

"""Классы"""

class Dataset:
    def __init__(self, filename='data.txt'):
        self.filename = filename
        self.data = self.read_file()
    def read_file(self):
        """
        Читает текстовый файл и сохраняет слова в self.data
        """
        try:
          with open(self.filename, 'r', encoding='utf-8') as file:
            text = file.read()

            #Очищаем текст и разбиваем по строкам
            return text.split('\n')

        except FileNotFoundError:
          print(f"Ошибка, файл '{filename}' не найден!")
        except Exception as e:
          print(f"Ошибка при чтении файла: {e}")

dataset = Dataset('data.txt')
dataset.read_file()
print(dataset.data, dataset.filename)

"""json"""

import json

class Dataset:
    def __init__(self, filename):
        self.filename = filename
        self.data = self._read_file()
    def _read_file(self):
        try:
          with open(self.filename, 'r', encoding='utf-8-sig') as file:
            data = json.load(file)
            return data
        except FileNotFoundError:
            print(f"Ошибка: файл '{self.filename}' не найден")
        except Exception as e:
            print(f"Ошибка при чтении файла: {e}")
    def get_song(self, num_id): #по id возвращает песню
        num_id = int(input())
        for song in data:
            if num_id == song['id']:
              return (f"Под номером {num_id} хранится песня {song['title']} автора {song['author']} :)")
    def find_similar(self, num_id):
      num_id = int(input())
      for song in data:
          if num_id == song['id']:
            s_ids = song['similar_ids']
            s_songs = []
            for s in s_ids:
              for song in data:
                if s == song['id']:
                  song_name = str(song['title']) + str(', ') + str(song['author'])
                  s_songs.append(song_name)
      string_songs = "; ".join(s_songs)
      return (f"Вот похожие песни: {string_songs}")

file_path = '/content/api.json'
dataset = Dataset(file_path)
print(dataset.filename)

dataset.get_song(file_path)

dataset.find_similar(file_path)